#!/usr/bin/env node

const { argv, exit, version, stdout, stderr } = await import('process');
const { runDusaCli } = await import('./lib/cli.js');

exit(
  runDusaCli(
    argv.slice(2),
    (s) => stdout.write(`${s}\n`),
    (s) => stderr.write(`${s}\n`),
  ),
);
