name: Check that everything builds correctly

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test-building:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci

      - name: Build package
        run: npm run lib

      - name: Build website
        run: npm run build

      - name: Build docs
        run: |
          cd docs
          npm ci
          npm run build
